#################################
# Port Number
#################################
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  banner:
    location: banner/banner.txt

  application:
    name: asd

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: true
    encoding: UTF-8

  #################################
  # MySQL Setting
  #################################
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatbot
    username: postgres
    password: '@dudgh0830'

  #################################
  # JPA Setting
  #################################
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #json?? ??
  jackson:
    serialization:
      fail-on-empty-beans: false


#
#  ###############################
#  # Security User ??? ?? ??
#  ###############################
#  security:
#    user:
#      name: test@test.com
#      password: 1111

###############################
# Log info
###############################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace